// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbbHmaPq0yk-AHwZAjDilsGWI-z_mCxSE',
    appId: '1:834924507782:android:bddc360f093956693a5707',
    messagingSenderId: '834924507782',
    projectId: 'auth-7fb43',
    storageBucket: 'auth-7fb43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs2m7y7UMn_NC7bSvbmkATVNcL9Cm2yy8',
    appId: '1:834924507782:ios:92c08b04164ce63f3a5707',
    messagingSenderId: '834924507782',
    projectId: 'auth-7fb43',
    storageBucket: 'auth-7fb43.appspot.com',
    iosClientId: '834924507782-73jcvhost06i8svtjt9ahdv9o50kpmue.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
